### ISSUE TITLE
Project Specific syntaxes are not working

### ISSUE THREAD

**Issue by jahan01** [facelessuser/ApplySyntax#93] opened 2016-01-20 08:25 UTC
I am trying to have project specific syntax. I added project_syntaxes json in my .sublime-project file but it is not working.

```
{
	"folders":
	[
		{
			"name": "BMS_Ubuntu",
			"path": ".",
		}
	],

    "project_syntaxes": [
        {
            "syntax": "Ansible/Ansible",
            "rules": [
                {"file_path": ".*\\\\ansible(\\\\..*)?$"},
            ]
        },
    ]
}
```

But the same is working if I do add this json in Settings-User, it is working as intended.

```
"syntaxes": [
        {
            "syntax": "Ansible/Ansible",
            "rules": [
                {"file_path": ".*\\\\ansible(\\\\..*)?$"},
            ]
        },
    ],
```

**Comment by facelessuser** [comment] 2016-01-20 16:12
It's possible there has been a regression somewhere along the way.  I will have to verify it.

**Comment by facelessuser** [comment] 2016-01-31 21:29
This should be fixed moving forward with the next release.

**Comment by facelessuser** [comment] 2016-03-02 18:16
It is possible, since I don't really use this feature, that I hastily patched the issue without understanding/remembering how project specific settings work with view settings. ref https://github.com/facelessuser/ApplySyntax/commit/bcb83d75b91e83ba9956ac74b9e21e5ce32476be#commitcomment-16452461.

**Comment by facelessuser** [comment] 2016-03-04 17:03
It appears no change was needed to the code.  The problem was not that the code was defective, but `project_syntaxes` should be placed under a `settings` keyword.

```js
"settings": {
    "project_syntaxes": [
        {
            "syntax": "Ansible/Ansible",
            "rules": [
                {"file_path": ".*\\\\ansible(\\\\..*)?$"},
            ]
        },
    ],
}
```

The current "fix" will be reverted.  Once the new version hits, please use proper setting format for project_syntaxes.  I simply don't use project specific settings much, so I simply forgot this was how it worked.  I will try and update the documentation accordingly.

**Closed** 2016-03-04 17:16 UTC
Labels: Accepted

**Comment by facelessuser** [comment] 2016-03-05 01:40
New version has been released reverting back to the old way.  The documentation now makes it clear how to set the project specific rules.
